[project]
name = "exampy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "cyclopts>=4.11.2",
    "dotenv>=0.9.9",
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.7.6",
    "mkdocs-mermaid2-plugin>=1.2.1",
    "mysql-connector-python>=9.7.0",
    "prompt-toolkit>=3.0.50",
    "pyright>=1.1.409",
    "tabulate>=0.10.0",
]

[project.scripts]
exampy = "main:main"

[build-system]
requires = ["hatchling>=1.21.0"]
build-backend = "hatchling.build"

[tool.uv]
package = true

[tool.hatch.build.targets.wheel]
packages = ["database", "shell"]

[tool.hatch.build.targets.wheel.force-include]
"main.py" = "main.py"
